---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ms-postgres.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "ms-postgres.name" . }}
  selector:
    matchLabels:
      app:  {{ include "ms-postgres.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ms-postgres.name" . }}
    spec:
      containers:
        - name: {{ include "ms-postgres.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        hostPath:
          path: {{ .Values.hostPath | default "/tmp/postgres" }}
          type: DirectoryOrCreate
